name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Use Node.js latest
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install node dependencies
        run: |
          npm i -g pnpm
          pnpm i
      - name: Run lint
        run: |
          pnpm run lint
      - name: Install emsdk
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
      - name: Build wasm
        run: |
          . emsdk/emsdk_env.sh
          pnpm run native
          pnpm run lib
          pnpm run wasm
      - name: Build
        run: |
          pnpm run build
      - name: Test
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          npx playwright install-deps
          pnpm run test
      - name: Release
        if: ${{ matrix.os == 'ubuntu-latest' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv dist my-ovpn-dist
          zip -r my-ovpn-dist.zip my-ovpn-dist
          gh release upload latest my-ovpn-dist.zip --clobber
